"""add rag_chunk table

Revision ID: 03ea827fb355
Revises: 4c3634037910
Create Date: 2026-09-09 22:35:46.309241

"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# Alembic 이 사용하는 리비전 식별자.
revision: str = '03ea827fb355'
down_revision: str | Sequence[str] | None = '4c3634037910'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rag_chunk',
    sa.Column('ingredient_id', sa.Uuid(), nullable=True, comment='관련 IngredientMaster. NIA Q&A는 한 성분에 매이지 않는 상황 설명이라 NULL 허용'),
    sa.Column('source_table', sa.Enum('evidence', 'ingredient_knowledge_fact', 'nia_qa', name='ragsourcetable', native_enum=False, length=30), nullable=False, comment='청크의 원본 소스'),
    sa.Column('evidence_id', sa.Uuid(), nullable=True),
    sa.Column('ingredient_knowledge_fact_id', sa.Uuid(), nullable=True),
    sa.Column('nia_record_id', sa.Text(), nullable=True, comment='NIA jsonl의 info.id. DB 테이블이 없는 소스라 FK 대신 문자열로 참조'),
    sa.Column('chunk_field', sa.Enum('evidence_claim', 'evidence_conditions', 'knowledge_efficacy', 'knowledge_recommended_skin_types', 'knowledge_precautions', 'knowledge_recommended_concentration', 'nia_question', 'nia_answer', 'nia_cot_step', name='ragchunkfield', native_enum=False, length=40), nullable=False, comment='원본의 어느 필드(의미단위)에서 나온 청크인지'),
    sa.Column('chunk_index', sa.Integer(), nullable=False, comment='같은 chunk_field 안에서의 순번. NIA_COT_STEP은 추론 단계 번호'),
    sa.Column('content', sa.Text(), nullable=False, comment='임베딩 대상 원문'),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False, comment='content의 임베딩 벡터'),
    sa.Column('embedding_model', sa.Text(), nullable=False, comment='벡터를 만든 임베딩 모델명. 모델이 바뀌면 이 값으로 재임베딩 대상을 가려낸다'),
    sa.Column('confidence_tier', sa.Enum('official_regulatory', 'structured_knowledge', 'ai_generated_reviewed', name='ragconfidencetier', native_enum=False, length=30), nullable=False, comment='사용자에게 출처를 보여줄 때 구분하는 신뢰도 등급'),
    sa.Column('cites_cir', sa.Boolean(), nullable=False, comment='IngredientKnowledgeFact의 원시 데이터 출처/저작권해결방안에 CIR 인용이 포함돼 있는지. CIR 안전성 근거 1단계(별도 스크래핑 없이 기존 텍스트에서 식별)'),
    sa.Column('source_title', sa.Text(), nullable=False, comment='출처 표시용 제목. 조회 시 원본 테이블 조인을 피하려 비정규화'),
    sa.Column('source_url', sa.Text(), nullable=True, comment='공식 출처 URL(Evidence). NIA Q&A는 NULL'),
    sa.Column('citation_refs', postgresql.ARRAY(sa.Text()), nullable=False, comment='PMID/DOI 등 인용 식별자 목록(NIA Q&A의 evidence_sources)'),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='레코드 고유 식별자'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='레코드 생성 시각(UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='레코드 최종 수정 시각(UTC)'),
    sa.CheckConstraint("(source_table = 'evidence' AND evidence_id IS NOT NULL   AND ingredient_knowledge_fact_id IS NULL AND nia_record_id IS NULL) OR (source_table = 'ingredient_knowledge_fact' AND evidence_id IS NULL   AND ingredient_knowledge_fact_id IS NOT NULL AND nia_record_id IS NULL) OR (source_table = 'nia_qa' AND evidence_id IS NULL   AND ingredient_knowledge_fact_id IS NULL AND nia_record_id IS NOT NULL)", name='ck_rag_chunk_exactly_one_source_ref'),
    sa.CheckConstraint("chunk_field IN ('evidence_claim', 'evidence_conditions', 'knowledge_efficacy', 'knowledge_recommended_skin_types', 'knowledge_precautions', 'knowledge_recommended_concentration', 'nia_question', 'nia_answer', 'nia_cot_step')", name='ck_rag_chunk_chunk_field'),
    sa.CheckConstraint("confidence_tier IN ('official_regulatory', 'structured_knowledge', 'ai_generated_reviewed')", name='ck_rag_chunk_confidence_tier'),
    sa.CheckConstraint("source_table IN ('evidence', 'ingredient_knowledge_fact', 'nia_qa')", name='ck_rag_chunk_source_table'),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient_master.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ingredient_knowledge_fact_id'], ['ingredient_knowledge_fact.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='RAG 검색·답변 생성에 쓰는 임베딩 청크. Evidence/IngredientKnowledgeFact/NIA Q&A 통합 인덱스',
    info={'managed': True}
    )
    op.create_index('ix_rag_chunk_embedding_hnsw', 'rag_chunk', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('ix_rag_chunk_ingredient_id', 'rag_chunk', ['ingredient_id'], unique=False)
    # ParadeDB pg_search BM25 인덱스. autogenerate가 모르는 인덱스 타입이라 수동으로 추가한다.
    # key_field는 이 인덱스가 결과를 원본 행에 되짚어 줄 때 쓰는 유일 식별자 컬럼이다.
    op.execute(
        "CREATE INDEX ix_rag_chunk_content_bm25 ON rag_chunk "
        "USING bm25 (id, content) WITH (key_field='id')"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS ix_rag_chunk_content_bm25")
    op.drop_index('ix_rag_chunk_ingredient_id', table_name='rag_chunk')
    op.drop_index('ix_rag_chunk_embedding_hnsw', table_name='rag_chunk', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('rag_chunk')
    # ### end Alembic commands ###
