"""add evidence_document evidence_chunk evidence_chunk_ingredient tables

Revision ID: 11cdc111cf27
Revises: d4c2a7e91b30
Create Date: 2026-09-15 17:22:23.060149

"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# Alembic 이 사용하는 리비전 식별자.
revision: str = '11cdc111cf27'
down_revision: str | Sequence[str] | None = 'd4c2a7e91b30'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidence_document',
    sa.Column('source_id', sa.Text(), nullable=False, comment='안정적 자연키(PMID:16766489, CIR 성분코드, MFDS 게시글ID 등). source_type과 묶어야 유일'),
    sa.Column('source_type', sa.Enum('mfds', 'cir', 'pubmed_abstract', 'regulatory_other', name='evidencedocumentsourcetype', native_enum=False, length=20), nullable=False, comment='근거 출처 종류'),
    sa.Column('source_title', sa.Text(), nullable=False, comment='문서 제목'),
    sa.Column('publisher', sa.Text(), nullable=True, comment='발행 기관/저널'),
    sa.Column('document_date', sa.Date(), nullable=True, comment='원 출처 발행/개정일'),
    sa.Column('url', sa.Text(), nullable=True, comment='출처 URL'),
    sa.Column('doi', sa.Text(), nullable=True),
    sa.Column('pmid', sa.Text(), nullable=True),
    sa.Column('jurisdiction', sa.Text(), nullable=True, comment='MFDS만 값 있음, CIR/PubMed는 보통 NULL'),
    sa.Column('language', sa.Text(), server_default='ko', nullable=False),
    sa.Column('evidence_level', sa.Enum('official_regulatory', 'expert_reviewed', 'peer_reviewed_study', name='evidencelevel', native_enum=False, length=30), nullable=False, comment='문서 자체의 출처 신뢰도 등급'),
    sa.Column('raw_ingredient_names', postgresql.ARRAY(sa.Text()), nullable=False, comment='원본 표기 그대로. 성분 FK 연결은 evidence_chunk_ingredient가 담당'),
    sa.Column('document_status', sa.Enum('final', 'amended_final', 'tentative', 'draft', 'rereview', 'unknown', name='evidencedocumentstatus', native_enum=False, length=20), nullable=True, comment='CIR 전용. MFDS/PubMed는 NULL'),
    sa.Column('study_type', sa.Enum('human_study', 'in_vitro', 'mixed_in_vitro_and_human', 'animal_study', 'review', 'unknown', name='evidencestudytype', native_enum=False, length=30), nullable=True, comment='PubMed 전용. MFDS/CIR는 NULL'),
    sa.Column('formulation_type', sa.Enum('single_ingredient', 'combination_formulation', name='evidenceformulationtype', native_enum=False, length=30), nullable=True, comment='PubMed 전용. 복합 제형(niacinamide+glycerin 등) 구분'),
    sa.Column('claim_topics', postgresql.ARRAY(sa.Text()), nullable=False, comment='이 문서가 다루는 claim 주제(EvidenceClaimTopic 값들)'),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='MFDS/CIR/PubMed 원문·metadata를 가져온 시각. created_at(레코드 생성 시각)과는 별개'),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='레코드 고유 식별자'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='레코드 생성 시각(UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='레코드 최종 수정 시각(UTC)'),
    sa.CheckConstraint("document_status IS NULL OR document_status IN ('final', 'amended_final', 'tentative', 'draft', 'rereview', 'unknown')", name='ck_evidence_document_document_status'),
    sa.CheckConstraint("evidence_level IN ('official_regulatory', 'expert_reviewed', 'peer_reviewed_study')", name='ck_evidence_document_evidence_level'),
    sa.CheckConstraint("formulation_type IS NULL OR formulation_type IN ('single_ingredient', 'combination_formulation')", name='ck_evidence_document_formulation_type'),
    sa.CheckConstraint("source_type IN ('mfds', 'cir', 'pubmed_abstract', 'regulatory_other')", name='ck_evidence_document_source_type'),
    sa.CheckConstraint("study_type IS NULL OR study_type IN ('human_study', 'in_vitro', 'mixed_in_vitro_and_human', 'animal_study', 'review', 'unknown')", name='ck_evidence_document_study_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_type', 'source_id', name='uq_evidence_document_source_type_source_id'),
    comment='MFDS/CIR/PubMed 근거 문서 단위 메타데이터. Claim(NIA)과 분리된 Evidence 전용',
    info={'managed': True}
    )
    op.create_table('evidence_chunk',
    sa.Column('document_id', sa.Uuid(), nullable=False, comment='citation locator 구성요소로 직접 쓰임(chunk_id 문자열 파싱 아님)'),
    sa.Column('chunk_id', sa.Text(), nullable=False, comment='결정적 자연키 "{source_id}:{page}:{section}:{chunk_index}". 재수집 매칭 전용'),
    sa.Column('source_type', sa.Enum('mfds', 'cir', 'pubmed_abstract', 'regulatory_other', name='evidencedocumentsourcetype', native_enum=False, length=20), nullable=False, comment='document에서 비정규화'),
    sa.Column('source_title', sa.Text(), nullable=False, comment='document에서 비정규화'),
    sa.Column('page', sa.Integer(), nullable=True, comment='CIR PDF만 값 있음'),
    sa.Column('section', sa.Text(), nullable=True, comment="PubMed는 'abstract' 고정, MFDS는 NULL"),
    sa.Column('chunk_index', sa.Integer(), nullable=False, comment='같은 document 안에서의 순번'),
    sa.Column('content', sa.Text(), nullable=False, comment='임베딩 대상 원문. 요약하지 않고 원문 그대로'),
    sa.Column('content_hash', sa.Text(), nullable=False, comment='content의 sha256. 재수집 시 원문 불변 여부 확인용'),
    sa.Column('parser_version', sa.Text(), nullable=False, comment='이 청크를 만든 파서/청킹 로직 버전'),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=False, comment='content의 임베딩 벡터. BAAI/bge-m3(local), 1024차원 - rag_chunk(1536)와 별도'),
    sa.Column('embedding_model', sa.Text(), nullable=False, comment='벡터를 만든 모델명'),
    sa.Column('url', sa.Text(), nullable=True, comment='document에서 비정규화'),
    sa.Column('doi', sa.Text(), nullable=True, comment='document에서 비정규화'),
    sa.Column('pmid', sa.Text(), nullable=True, comment='document에서 비정규화'),
    sa.Column('jurisdiction', sa.Text(), nullable=True, comment='document에서 비정규화'),
    sa.Column('evidence_level', sa.Enum('official_regulatory', 'expert_reviewed', 'peer_reviewed_study', name='evidencelevel', native_enum=False, length=30), nullable=False, comment='document에서 비정규화'),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='레코드 고유 식별자'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='레코드 생성 시각(UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='레코드 최종 수정 시각(UTC)'),
    sa.CheckConstraint("evidence_level IN ('official_regulatory', 'expert_reviewed', 'peer_reviewed_study')", name='ck_evidence_chunk_evidence_level'),
    sa.CheckConstraint("source_type IN ('mfds', 'cir', 'pubmed_abstract', 'regulatory_other')", name='ck_evidence_chunk_source_type'),
    sa.ForeignKeyConstraint(['document_id'], ['evidence_document.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chunk_id', name='uq_evidence_chunk_chunk_id'),
    comment='Evidence RAG(MFDS/CIR/PubMed) 검색·임베딩 청크. Claim(NIA)과 분리된 저장소',
    info={'managed': True}
    )
    op.create_index('ix_evidence_chunk_document_id', 'evidence_chunk', ['document_id'], unique=False)
    op.create_index('ix_evidence_chunk_embedding_hnsw', 'evidence_chunk', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_table('evidence_chunk_ingredient',
    sa.Column('evidence_chunk_id', sa.Uuid(), nullable=False),
    sa.Column('ingredient_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_chunk_id'], ['evidence_chunk.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient_master.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('evidence_chunk_id', 'ingredient_id', name='pk_evidence_chunk_ingredient'),
    comment='evidence_chunk ↔ ingredient_master 다대다. 청크 하나가 병용/충돌/비교처럼 여러 성분을 동시에 다룰 수 있어 단일 FK 대신 조인 테이블로 뗀다',
    info={'managed': True}
    )
    op.create_index('ix_evidence_chunk_ingredient_ingredient_id', 'evidence_chunk_ingredient', ['ingredient_id', 'evidence_chunk_id'], unique=False)
    # 아래 두 줄은 autogenerate가 잘못 감지한 삭제 대상이라 수동으로 제거했다 - rag_chunk의
    # BM25/자연키 인덱스는 ORM 모델에 선언돼 있지 않고(raw SQL로만 관리, 03ea827fb355/
    # 0ff194fd5f2f 마이그레이션 참고) autogenerate가 매번 "삭제됨"으로 오판한다
    # (docs/erd/app.md의 rag_chunk 절에 이미 기록된 기존 이슈). 이번 변경 범위(evidence_*
    # 테이블 추가)와 무관하므로 건드리지 않는다.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # rag_chunk의 BM25/자연키 인덱스 재생성 코드는 upgrade()와 같은 이유로 제거했다(위 주석 참고) -
    # 이번 마이그레이션이 손대지 않았으니 되돌릴 필요도 없다.
    op.drop_index('ix_evidence_chunk_ingredient_ingredient_id', table_name='evidence_chunk_ingredient')
    op.drop_table('evidence_chunk_ingredient')
    op.drop_index('ix_evidence_chunk_embedding_hnsw', table_name='evidence_chunk', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index('ix_evidence_chunk_document_id', table_name='evidence_chunk')
    op.drop_table('evidence_chunk')
    op.drop_table('evidence_document')
    # ### end Alembic commands ###
