"""add chat_room chat_message chat_turn_state tables

Revision ID: 2063ce3feae3
Revises: 3165318c750d
Create Date: 2026-09-20 14:26:31.668231

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# Alembic 이 사용하는 리비전 식별자.
revision: str = "2063ce3feae3"
down_revision: str | Sequence[str] | None = "3165318c750d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat_room",
        sa.Column(
            "user_id",
            sa.Uuid(),
            nullable=False,
            comment="방 소유 사용자. 계정 삭제 시 대화도 함께 삭제한다. 로그인 사용자 전용이라 NULL 없음",
        ),
        sa.Column(
            "thread_id",
            sa.Uuid(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="LangGraph 체크포인터 네임스페이스(AuthorizedRoom.thread_id)",
        ),
        sa.Column(
            "schema_version",
            sa.Integer(),
            server_default=sa.text("1"),
            nullable=False,
            comment="SessionSnapshot.schema_version 그대로 저장",
        ),
        sa.Column(
            "source_revision",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
            comment="낙관적 잠금 카운터. 턴이 커밋될 때마다 +1, SaveSummaryRequest.expected_revision 과 비교",
        ),
        sa.Column(
            "last_completed_request_id",
            sa.Text(),
            nullable=True,
            comment="멱등성 확인용. 마지막으로 완전히 커밋된 턴의 request_id",
        ),
        sa.Column(
            "profile",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
            comment="UserProfile 직렬화",
        ),
        sa.Column(
            "task_context",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
            comment="TaskContext 직렬화",
        ),
        sa.Column(
            "pending_question",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="PendingQuestion 직렬화",
        ),
        sa.Column(
            "candidate_set",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="ProductCandidateSet 직렬화. 가장 최근 것 하나만",
        ),
        sa.Column(
            "routine",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="RoutinePlan 직렬화. 가장 최근 것 하나만",
        ),
        sa.Column(
            "evidence",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
            comment="EvidenceRecord 목록 직렬화",
        ),
        sa.Column(
            "summary",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="ConversationSummary 직렬화",
        ),
        sa.Column(
            "id",
            sa.Uuid(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="레코드 고유 식별자",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="레코드 생성 시각(UTC)",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="레코드 최종 수정 시각(UTC)",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["app_user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("thread_id", name="uq_chat_room_thread_id"),
        sa.UniqueConstraint("user_id", name="uq_chat_room_user_id"),
        comment="로그인 사용자의 채팅방. 사용자당 1개이며 Agent 세션 스냅샷을 담는다",
        info={"managed": True},
    )
    op.create_table(
        "chat_message",
        sa.Column(
            "chat_room_id",
            sa.Uuid(),
            nullable=False,
            comment="소속 채팅방. 방이 삭제되면 함께 삭제한다",
        ),
        sa.Column(
            "request_id", sa.Text(), nullable=False, comment="이 메시지를 만든 턴의 request_id"
        ),
        sa.Column(
            "role",
            sa.Enum("user", "assistant", name="messagerole", native_enum=False, length=16),
            nullable=False,
            comment="user/assistant",
        ),
        sa.Column("content", sa.Text(), nullable=False, comment="본문"),
        sa.Column("sequence", sa.Integer(), nullable=False, comment="방 내 순번. 1부터 증가"),
        sa.Column(
            "id",
            sa.Uuid(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="레코드 고유 식별자",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="레코드 생성 시각(UTC)",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="레코드 최종 수정 시각(UTC)",
        ),
        sa.ForeignKeyConstraint(["chat_room_id"], ["chat_room.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "chat_room_id", "request_id", "role", name="uq_chat_message_room_request_role"
        ),
        sa.UniqueConstraint("chat_room_id", "sequence", name="uq_chat_message_room_sequence"),
        comment="채팅방 안의 메시지 한 건",
        info={"managed": True},
    )
    op.create_table(
        "chat_turn_state",
        sa.Column(
            "chat_room_id",
            sa.Uuid(),
            nullable=False,
            comment="소속 채팅방. 방이 삭제되면 함께 삭제한다",
        ),
        sa.Column("request_id", sa.Text(), nullable=False, comment="턴 요청 식별자"),
        sa.Column(
            "input_fingerprint",
            sa.Text(),
            nullable=False,
            comment="같은 request_id 로 다른 입력이 재요청되면 REQUEST_CONFLICT 판정에 사용",
        ),
        sa.Column(
            "status",
            sa.Enum(
                "in_progress",
                "staged",
                "completed",
                "failed",
                name="turnstatestatus",
                native_enum=False,
                length=16,
            ),
            nullable=False,
            comment="in_progress/staged/completed/failed",
        ),
        sa.Column(
            "staged_output",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="ChatTurnOutput 직렬화. complete_turn 전 임시 보관",
        ),
        sa.Column(
            "staged_snapshot",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="SessionSnapshot 직렬화. staged_output 과 같은 시점에 임시 보관",
        ),
        sa.Column(
            "failure_code",
            sa.Enum("graph", "storage", name="turnfailurecode", native_enum=False, length=16),
            nullable=True,
            comment="graph/storage",
        ),
        sa.Column("failure_detail", sa.Text(), nullable=True, comment="실패 상세"),
        sa.Column("retryable", sa.Boolean(), nullable=True, comment="재시도 가능 여부"),
        sa.Column(
            "id",
            sa.Uuid(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
            comment="레코드 고유 식별자",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="레코드 생성 시각(UTC)",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="레코드 최종 수정 시각(UTC)",
        ),
        sa.ForeignKeyConstraint(["chat_room_id"], ["chat_room.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("chat_room_id", "request_id", name="uq_chat_turn_state_room_request"),
        comment="채팅 턴의 생애주기와 request_id 재요청 충돌 감지",
        info={"managed": True},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("chat_turn_state")
    op.drop_table("chat_message")
    op.drop_table("chat_room")
    # ### end Alembic commands ###
