"""add claim_document claim_chunk claim_chunk_ingredient tables

Revision ID: 3165318c750d
Revises: 11cdc111cf27
Create Date: 2026-09-17 14:53:07.823872

"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# Alembic 이 사용하는 리비전 식별자.
revision: str = '3165318c750d'
down_revision: str | Sequence[str] | None = '11cdc111cf27'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claim_document',
    sa.Column('source_record_id', sa.Text(), nullable=False, comment='NiaLabelingDocument.source.record_id'),
    sa.Column('annotation_version', sa.Text(), nullable=False, comment='라벨링 실행 식별자(pilot/validation/production 구분). source_record_id와 묶어야 유일'),
    sa.Column('schema_version', sa.Text(), nullable=False, comment='ClaimDocument(Pydantic) schema_version'),
    sa.Column('dataset_split', sa.Enum('training', 'validation', name='claimdatasetsplit', native_enum=False, length=20), nullable=False, comment='training/validation'),
    sa.Column('skin_concerns_raw', postgresql.ARRAY(sa.Text()), nullable=False, comment='NiaLabelingDocument.case_context.skin_concerns_raw'),
    sa.Column('production_ready', sa.Boolean(), nullable=False, comment='사람 최종 검수 완료 여부(NiaLabelingDocument.production_ready). runtime 필수 필터로 강제하지 않는다'),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='레코드 고유 식별자'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='레코드 생성 시각(UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='레코드 최종 수정 시각(UTC)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_record_id', 'annotation_version', name='uq_claim_document_record_annotation'),
    comment='NIA Claim 원본 레코드 단위 provenance. Evidence와 분리된 Claim 전용',
    info={'managed': True}
    )
    op.create_table('claim_chunk',
    sa.Column('claim_document_id', sa.Uuid(), nullable=False, comment='이 statement가 속한 NIA 레코드/annotation run'),
    sa.Column('statement_id', sa.Text(), nullable=False, comment='ClaimDocument(Pydantic).statement_id. annotation run마다 재사용되므로 claim_document_id와 묶어야 유일'),
    sa.Column('statement_type', sa.Enum('case_observation', 'cause_claim', 'ingredient_effect_claim', 'precaution', 'usage_instruction', 'combination_claim', 'contextual_factor', name='claimstatementtype', native_enum=False, length=30), nullable=False),
    sa.Column('content', sa.Text(), nullable=False, comment='임베딩 대상 원문. ClaimDocument.content(mapper가 이미 통일한 텍스트)'),
    sa.Column('source_spans', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='ClaimDocument.source_spans(json_path/quote/start/end) 그대로. 원문 재검증용'),
    sa.Column('decision', sa.Enum('blocked', 'human_review', 'ingestible_structured', 'ingestible_free_text', name='claimingestiondecision', native_enum=False, length=25), nullable=False, comment='운영 검색 인덱스 필터. ingestible_* 만 기본 검색 대상(Shared Decisions #6)'),
    sa.Column('priority', sa.Enum('primary', 'secondary', name='claimpriority', native_enum=False, length=15), nullable=False),
    sa.Column('support_status', sa.Enum('unverified', 'supported', 'contradicted', 'insufficient', name='claimsupportstatus', native_enum=False, length=15), nullable=False, comment='현재 파이프라인은 항상 unverified'),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=False, comment='content의 임베딩 벡터. BAAI/bge-m3(local), 1024차원'),
    sa.Column('embedding_model', sa.Text(), nullable=False, comment='벡터를 만든 모델명'),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='레코드 고유 식별자'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='레코드 생성 시각(UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='레코드 최종 수정 시각(UTC)'),
    sa.CheckConstraint("decision IN ('blocked', 'human_review', 'ingestible_structured', 'ingestible_free_text')", name='ck_claim_chunk_decision'),
    sa.CheckConstraint("priority IN ('primary', 'secondary')", name='ck_claim_chunk_priority'),
    sa.CheckConstraint("statement_type IN ('case_observation', 'cause_claim', 'ingredient_effect_claim', 'precaution', 'usage_instruction', 'combination_claim', 'contextual_factor')", name='ck_claim_chunk_statement_type'),
    sa.CheckConstraint("support_status IN ('unverified', 'supported', 'contradicted', 'insufficient')", name='ck_claim_chunk_support_status'),
    sa.ForeignKeyConstraint(['claim_document_id'], ['claim_document.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('claim_document_id', 'statement_id', name='uq_claim_chunk_document_statement'),
    comment='NIA Claim statement 단위 검색·임베딩 청크. Evidence와 분리된 Claim 전용',
    info={'managed': True}
    )
    op.create_index('ix_claim_chunk_decision', 'claim_chunk', ['decision'], unique=False)
    op.create_index('ix_claim_chunk_document_id', 'claim_chunk', ['claim_document_id'], unique=False)
    op.create_index('ix_claim_chunk_embedding_hnsw', 'claim_chunk', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_table('claim_chunk_ingredient',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('claim_chunk_id', sa.Uuid(), nullable=False),
    sa.Column('ingredient_id', sa.Uuid(), nullable=True, comment="matching_status='matched'일 때만 non-null"),
    sa.Column('raw_name', sa.Text(), nullable=True, comment='IngredientRef.raw_name - unresolved든 matched든 원문 있으면 보존'),
    sa.Column('matching_status', sa.Enum('unresolved', 'unresolved_ambiguous_family', 'matched', 'rejected', name='claimingredientmatchingstatus', native_enum=False, length=30), nullable=False),
    sa.Column('role', sa.Enum('primary', 'secondary', 'unspecified', name='claimingredientrefrole', native_enum=False, length=15), nullable=False),
    sa.CheckConstraint("matching_status IN ('unresolved', 'unresolved_ambiguous_family', 'matched', 'rejected')", name='ck_claim_chunk_ingredient_matching_status'),
    sa.CheckConstraint("role IN ('primary', 'secondary', 'unspecified')", name='ck_claim_chunk_ingredient_role'),
    sa.CheckConstraint('ingredient_id IS NOT NULL OR raw_name IS NOT NULL', name='ck_claim_chunk_ingredient_has_identity'),
    sa.ForeignKeyConstraint(['claim_chunk_id'], ['claim_chunk.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient_master.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='claim_chunk ↔ ingredient_master 연결. unresolved(raw_name만 있는) 언급도 보존',
    info={'managed': True}
    )
    op.create_index('ix_claim_chunk_ingredient_claim_chunk_id', 'claim_chunk_ingredient', ['claim_chunk_id'], unique=False)
    op.create_index('ix_claim_chunk_ingredient_ingredient_id', 'claim_chunk_ingredient', ['ingredient_id', 'claim_chunk_id'], unique=False)
    # 아래 두 줄은 autogenerate가 잘못 감지한 삭제 대상이라 수동으로 제거했다 - rag_chunk의
    # BM25/자연키 인덱스는 ORM 모델에 선언돼 있지 않고(raw SQL로만 관리, 03ea827fb355/
    # 0ff194fd5f2f 마이그레이션 참고) autogenerate가 매번 "삭제됨"으로 오판한다(11cdc111cf27
    # 마이그레이션에서도 동일 이슈 발생, docs/erd/app.md의 rag_chunk 절에 이미 기록된 기존
    # 이슈). 이번 변경 범위(claim_* 테이블 추가)와 무관하므로 건드리지 않는다.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # rag_chunk의 BM25/자연키 인덱스 재생성 코드는 upgrade()와 같은 이유로 제거했다(위 주석 참고) -
    # 이번 마이그레이션이 손대지 않았으니 되돌릴 필요도 없다.
    op.drop_index('ix_claim_chunk_ingredient_ingredient_id', table_name='claim_chunk_ingredient')
    op.drop_index('ix_claim_chunk_ingredient_claim_chunk_id', table_name='claim_chunk_ingredient')
    op.drop_table('claim_chunk_ingredient')
    op.drop_index('ix_claim_chunk_embedding_hnsw', table_name='claim_chunk', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index('ix_claim_chunk_document_id', table_name='claim_chunk')
    op.drop_index('ix_claim_chunk_decision', table_name='claim_chunk')
    op.drop_table('claim_chunk')
    op.drop_table('claim_document')
    # ### end Alembic commands ###
