"""add product ingredient snapshot and match tables

Revision ID: 459db45c7a64
Revises: 0ff194fd5f2f
Create Date: 2026-09-10 01:34:03.054576

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Alembic 이 사용하는 리비전 식별자.
revision: str = '459db45c7a64'
down_revision: str | Sequence[str] | None = '0ff194fd5f2f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_ingredient_snapshot',
    sa.Column('source', sa.Text(), nullable=False, comment="예: 'oliveyoung_global'. candidate_id는 여기 쓰지 않는다"),
    sa.Column('source_product_id', sa.Text(), nullable=False, comment='쇼핑몰 상품 ID(candidate_id 아님 - 재수집마다 안 바뀌는 영구 식별자)'),
    sa.Column('raw_ingredients_text', sa.Text(), nullable=False, comment='원문 그대로. 재현·재검토 기준'),
    sa.Column('raw_text_hash', sa.Text(), nullable=False, comment='raw_ingredients_text의 해시(sha256). 재수집 시 내용 불변 여부를 빠르게 확인'),
    sa.Column('parser_version', sa.Text(), nullable=False, comment='이 스냅샷을 토큰화한 파서 버전. 파서가 바뀌면(예: 새 구분자 처리 추가) 이 값으로 재파싱 대상을 가려낸다'),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='레코드 고유 식별자'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='레코드 생성 시각(UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='레코드 최종 수정 시각(UTC)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_product_id', 'raw_text_hash', name='uq_product_ingredient_snapshot_source_product_hash'),
    comment='상품 전성분(INCI) 원문 스냅샷. source+source_product_id+원문 해시로 중복 방지',
    info={'managed': True}
    )
    op.create_table('product_ingredient',
    sa.Column('snapshot_id', sa.Uuid(), nullable=False),
    sa.Column('section_sequence', sa.Integer(), nullable=False, comment='원문 안 구간(옵션 라벨) 순서. 0부터'),
    sa.Column('section_label', sa.Text(), nullable=True, comment='원문 그대로의 [라벨] 텍스트. 구간이 없으면 NULL'),
    sa.Column('section_link_status', sa.Enum('no_option_sections', 'linked', 'ambiguous', name='productingredientsectionlinkstatus', native_enum=False, length=20), nullable=False, comment='이 구간이 실제 판매 옵션과 연결됐는지(LINKED만 특정 옵션의 성분으로 쓸 수 있음)'),
    sa.Column('linked_option_gds_cd', sa.Text(), nullable=True, comment='section_link_status=LINKED일 때만 채워지는 판매 옵션 식별자(gds_cd)'),
    sa.Column('token_order', sa.Integer(), nullable=False, comment='구간 안에서 성분이 나열된 순서. 0부터'),
    sa.Column('raw_token', sa.Text(), nullable=False, comment='원문 그대로(구분자 분리 + 트리밍만). 매칭 실패해도 보존'),
    sa.Column('matching_name', sa.Text(), nullable=False, comment='매칭에 실제로 쓴 이름(함량 괄호 제거, 상용명 괄호는 보존)'),
    sa.Column('concentration_text', sa.Text(), nullable=True, comment='괄호 안 함량 표기 원문(있으면)'),
    sa.Column('token_parse_status', sa.Enum('parsed', 'needs_review', name='productingredienttokenparsestatus', native_enum=False, length=20), nullable=False, comment='NEEDS_REVIEW면 raw_token이 두 성분명이 붙은 것일 수 있어 매칭을 시도하지 않는다'),
    sa.Column('token_review_reason', sa.Text(), nullable=True, comment='token_parse_status=NEEDS_REVIEW일 때만 채워짐'),
    sa.Column('ingredient_id', sa.Uuid(), nullable=True, comment='매칭된 표준 성분. 미매칭이면 NULL(행은 유지)'),
    sa.Column('match_method', sa.Text(), nullable=True, comment='IngredientNameMatcher가 반환한 IngredientMatchMethod 값. 시도 전이면 NULL'),
    sa.Column('match_acceptance', sa.Enum('confirmed', 'needs_review', 'unmatched', name='ingredientmatchacceptance', native_enum=False, length=20), nullable=False, comment='CONFIRMED만 RAG 근거 연결에 쓴다. matcher 결과가 있어도 method가 영문 정규화 일치가 아니면 NEEDS_REVIEW로 내린다(matcher 자체는 수정하지 않는다)'),
    sa.Column('match_review_reason', sa.Text(), nullable=True, comment='match_acceptance != CONFIRMED일 때 왜 자동 확정하지 않았는지'),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='레코드 고유 식별자'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='레코드 생성 시각(UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='레코드 최종 수정 시각(UTC)'),
    sa.CheckConstraint("match_acceptance IN ('confirmed', 'needs_review', 'unmatched')", name='ck_product_ingredient_match_acceptance'),
    sa.CheckConstraint("section_link_status IN ('no_option_sections', 'linked', 'ambiguous')", name='ck_product_ingredient_section_link_status'),
    sa.CheckConstraint("token_parse_status IN ('parsed', 'needs_review')", name='ck_product_ingredient_token_parse_status'),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient_master.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['product_ingredient_snapshot.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_id', 'section_sequence', 'token_order', name='uq_product_ingredient_snapshot_position'),
    comment='전성분 원문의 성분 토큰 하나 + IngredientMaster 매칭 결과',
    info={'managed': True}
    )
    op.create_index('ix_product_ingredient_ingredient_id', 'product_ingredient', ['ingredient_id'], unique=False)
    # ix_rag_chunk_content_bm25/ux_rag_chunk_natural_key는 이 파일이 만드는 테이블과
    # 무관하다 - autogenerate가 이 두 인덱스를 "제거 대상"으로 잡은 건 그 인덱스들이
    # rag_chunk.py 모델에 선언 없이(원시 SQL로) DB에만 있어서다. 여기서 지우면 안 되므로
    # 자동 생성된 drop_index 두 줄은 뺐다(재적재 안전성 작업의 별도 마이그레이션 대상).
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_product_ingredient_ingredient_id', table_name='product_ingredient')
    op.drop_table('product_ingredient')
    op.drop_table('product_ingredient_snapshot')
    # ### end Alembic commands ###
