"""add knowledgedata chemical and licensing columns

Revision ID: 4c3634037910
Revises: f2fafa99fb94
Create Date: 2026-09-09 22:31:22.711011

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Alembic 이 사용하는 리비전 식별자.
revision: str = '4c3634037910'
down_revision: str | Sequence[str] | None = 'f2fafa99fb94'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredient_knowledge_fact', sa.Column('chemical_properties', sa.Text(), nullable=True, comment='화학적물성'))
    op.add_column('ingredient_knowledge_fact', sa.Column('product_characteristics', sa.Text(), nullable=True, comment='제품적특성'))
    op.add_column('ingredient_knowledge_fact', sa.Column('solubility', sa.Text(), nullable=True, comment='용해도'))
    op.add_column('ingredient_knowledge_fact', sa.Column('molecular_formula', sa.Text(), nullable=True, comment='분자식'))
    op.add_column('ingredient_knowledge_fact', sa.Column('molecular_weight', sa.Text(), nullable=True, comment='분자량'))
    op.add_column('ingredient_knowledge_fact', sa.Column('copyright_resolution', sa.Text(), nullable=True, comment='저작권해결방안. 행별 출처 라이선스 근거(예: 공공데이터/이용허락계약)'))
    op.add_column('ingredient_knowledge_fact', sa.Column('token_count', sa.Text(), nullable=True, comment='토큰. 원본이 단일 숫자가 아닌 경우가 있어 문자열로 그대로 보존'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingredient_knowledge_fact', 'token_count')
    op.drop_column('ingredient_knowledge_fact', 'copyright_resolution')
    op.drop_column('ingredient_knowledge_fact', 'molecular_weight')
    op.drop_column('ingredient_knowledge_fact', 'molecular_formula')
    op.drop_column('ingredient_knowledge_fact', 'solubility')
    op.drop_column('ingredient_knowledge_fact', 'product_characteristics')
    op.drop_column('ingredient_knowledge_fact', 'chemical_properties')
    # ### end Alembic commands ###
