"""add ingredient_knowledge_fact table

Revision ID: 6e7ffc9706e8
Revises: db7c30b372f2
Create Date: 2026-09-09 17:46:28.170688

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Alembic 이 사용하는 리비전 식별자.
revision: str = '6e7ffc9706e8'
down_revision: str | Sequence[str] | None = 'db7c30b372f2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredient_knowledge_fact',
    sa.Column('ingredient_id', sa.Uuid(), nullable=False, comment='매칭된 IngredientMaster 레코드. 매칭 실패 행은 여기 적재하지 않고 수동 검토 큐로 보낸다'),
    sa.Column('source_row_no', sa.Integer(), nullable=False, comment="Knowledgedata.xlsx의 'No' 컬럼(원본 행 식별자)"),
    sa.Column('inci_name', sa.Text(), nullable=False, comment="원본 '성분명(INCI)' 컬럼"),
    sa.Column('name_ko', sa.Text(), nullable=True, comment="원본 '한글명' 컬럼"),
    sa.Column('efficacy', sa.Text(), nullable=True, comment='효능'),
    sa.Column('recommended_skin_types', sa.Text(), nullable=True, comment='권장피부타입(원본 자유 텍스트)'),
    sa.Column('precautions', sa.Text(), nullable=True, comment='사용상주의사항(안전성)'),
    sa.Column('recommended_concentration', sa.Text(), nullable=True, comment="권장농도(원본 자유 텍스트, 예: '0.5~7.0%')"),
    sa.Column('compounding_regulation_text', sa.Text(), nullable=True, comment='배합규제 원문. 국가가 혼재돼 있어 MFDS 교차검증 전에는 국내 기준으로 쓰지 않는다'),
    sa.Column('raw_material_source', sa.Text(), nullable=True, comment='원료출처'),
    sa.Column('source_reference', sa.Text(), nullable=True, comment='원시 데이터 출처(참고문헌 file명)'),
    sa.Column('regulatory_confidence', sa.Enum('verified', 'unverified', name='regulatoryconfidence', native_enum=False, length=20), nullable=False, comment='compounding_regulation_text가 MFDS와 교차검증됐는지 여부'),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='레코드 고유 식별자'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='레코드 생성 시각(UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='레코드 최종 수정 시각(UTC)'),
    sa.CheckConstraint("regulatory_confidence IN ('verified', 'unverified')", name='ck_ingredient_knowledge_fact_regulatory_confidence'),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient_master.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_row_no', name='uq_ingredient_knowledge_fact_source_row_no'),
    comment='Knowledgedata.xlsx 정제 결과. RAG Document 생성의 입력',
    info={'managed': True}
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ingredient_knowledge_fact')
    # ### end Alembic commands ###
