"""add product table

Revision ID: 7b85bd9f1045
Revises: 993200358dfb
Create Date: 2026-09-10 16:20:57.336328

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# Alembic 이 사용하는 리비전 식별자.
revision: str = '7b85bd9f1045'
down_revision: str | Sequence[str] | None = '993200358dfb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('source', sa.Text(), nullable=False, comment="예: 'oliveyoung_global'. product_ingredient_snapshot.source와 값을 맞춘다"),
    sa.Column('source_product_id', sa.Text(), nullable=False, comment='쇼핑몰 상품 ID. candidate_id(수집 실행 순번)는 저장하지 않는다'),
    sa.Column('search_query', sa.Text(), nullable=False, comment="이 행을 찾은 검색어. 카테고리 전수 크롤링이면 'category:<코드>'"),
    sa.Column('target_group', sa.Enum('아스코빅애씨드', '나이아신아마이드', '레티놀', '글라이콜릭애씨드', '살리실릭애씨드', name='producttargetgroup', native_enum=False, length=20), nullable=True, comment='성분 키워드 검색으로 모은 행만 채움. 카테고리 크롤링 행은 NULL'),
    sa.Column('raw_title', sa.Text(), nullable=False, comment='수집한 원본 상품명. 고치지 않는다 — 재매칭의 기준'),
    sa.Column('display_title', sa.Text(), nullable=False, comment='화면 노출용 한글 상품명'),
    sa.Column('title_source', sa.Enum('native_kr', 'oliveyoung_kr', 'translated', 'untranslated', name='producttitlesource', native_enum=False, length=20), nullable=False, comment='display_title의 신뢰도 구분. TRANSLATED/UNTRANSLATED는 공식명 아님'),
    sa.Column('brand', sa.Text(), nullable=False, comment='브랜드명'),
    sa.Column('maker', sa.Text(), nullable=True, comment='제조사. 소스가 안 주면 NULL'),
    sa.Column('category1', sa.Text(), nullable=False, comment='대분류'),
    sa.Column('category2', sa.Text(), nullable=True, comment='중분류'),
    sa.Column('category3', sa.Text(), nullable=True, comment='소분류'),
    sa.Column('lowest_price', sa.Integer(), nullable=False, comment='올리브영 글로벌: 할인가(실제 지불가). 네이버 쇼핑: 판매처 간 최저가'),
    sa.Column('highest_price', sa.Integer(), nullable=False, comment='올리브영 글로벌: 정가. 네이버 쇼핑: 판매처 간 최고가'),
    sa.Column('price_band', sa.Enum('1만원 미만', '1만원대', '2만원대', '3~4만원대', '5만원 이상', name='productpriceband', native_enum=False, length=20), nullable=False, comment='lowest_price 기준 가격대'),
    sa.Column('volume_value', sa.Numeric(), nullable=True, comment='제목에서 추출한 단일 용량. 복수/세트/미확정이면 NULL(0 아님)'),
    sa.Column('volume_unit', sa.Text(), nullable=True, comment="예: 'ml', 'g'"),
    sa.Column('image_url', sa.Text(), nullable=False, comment='원본 이미지 URL'),
    sa.Column('local_image_path', sa.Text(), nullable=False, comment='저장소 루트 기준 상대경로. DB만 넘기면 이미지 파일은 안 따라간다'),
    sa.Column('shopping_url', sa.Text(), nullable=False, comment='상품 상세 페이지 URL'),
    sa.Column('mall_name', sa.Text(), nullable=False, comment='판매처명'),
    sa.Column('product_type', sa.Text(), nullable=False, comment="현재 관측값 'GENERAL_PRODUCT' 하나뿐이라 아직 Enum으로 좁히지 않음"),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False, comment='이 상태를 수집한 시각(크롤러 관측 시각)'),
    sa.Column('match_status', sa.Enum('matched', 'manual_review_required', 'rejected', name='productmatchstatus', native_enum=False, length=30), nullable=False, comment='수집 직후는 항상 MANUAL_REVIEW_REQUIRED. 전성분 검증 전 자동 MATCHED 없음'),
    sa.Column('review_reasons', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False, comment='검토가 필요한 구체적 사유들(ReviewReason 값). 비어 있어도 검토 완료 아님'),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='레코드 고유 식별자'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='레코드 생성 시각(UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='레코드 최종 수정 시각(UTC)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_product_id', name='uq_product_source_product_id'),
    comment='상품 카탈로그(이름·가격·이미지)의 최신 상태. 이력 저장소 아님',
    info={'managed': True}
    )
    # ### end Alembic commands ###
    # 주의: autogenerate가 rag_chunk의 pg_search BM25 인덱스(ix_rag_chunk_content_bm25)와
    # ux_rag_chunk_natural_key를 "삭제 대상"으로 잘못 감지해 넣은 drop_index 2줄을 뺐다 -
    # 이 인덱스들은 SQLAlchemy 모델에 선언돼 있지 않을 뿐 실제로는 존재하는 인덱스라,
    # 그대로 뒀으면 이번 마이그레이션과 무관하게 지워질 뻔했다.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    # ### end Alembic commands ###
