"""update ingredient_knowledge_fact source_row_no comment

Revision ID: aa0819863b09
Revises: 6e7ffc9706e8
Create Date: 2026-09-09 17:47:57.570369

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Alembic 이 사용하는 리비전 식별자.
revision: str = 'aa0819863b09'
down_revision: str | Sequence[str] | None = '6e7ffc9706e8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ingredient_knowledge_fact', 'source_row_no',
               existing_type=sa.INTEGER(),
               comment="Knowledgedata.xlsx의 실제 엑셀 행 번호. 원본 'No' 컬럼은 2,465개 중 451개가 비어 있어 식별자로 쓰지 않는다",
               existing_comment="Knowledgedata.xlsx의 'No' 컬럼(원본 행 식별자)",
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ingredient_knowledge_fact', 'source_row_no',
               existing_type=sa.INTEGER(),
               comment="Knowledgedata.xlsx의 'No' 컬럼(원본 행 식별자)",
               existing_comment="Knowledgedata.xlsx의 실제 엑셀 행 번호. 원본 'No' 컬럼은 2,465개 중 451개가 비어 있어 식별자로 쓰지 않는다",
               existing_nullable=False)
    # ### end Alembic commands ###
