"""add app_user table

Revision ID: b1f97294c64e
Revises: f2fafa99fb94
Create Date: 2026-09-10 06:56:59.090671

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Alembic 이 사용하는 리비전 식별자.
revision: str = 'b1f97294c64e'
down_revision: str | Sequence[str] | None = 'f2fafa99fb94'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('email', sa.Text(), nullable=False, comment='로그인 식별자. 대소문자를 구분하지 않도록 저장 전에 소문자로 정규화한다'),
    sa.Column('hashed_password', sa.Text(), nullable=False, comment='argon2id 해시 문자열. 원문 비밀번호는 저장하지 않는다'),
    sa.Column('name', sa.Text(), nullable=False, comment='사용자 표시 이름'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='비활성 계정은 로그인과 세션 검증을 모두 거부한다'),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='레코드 고유 식별자'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='레코드 생성 시각(UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='레코드 최종 수정 시각(UTC)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_app_user_email'),
    comment='이메일/비밀번호 로그인 사용자 계정',
    info={'managed': True}
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_user')
    # ### end Alembic commands ###
