"""add gender/age_group/terms_agreed fields to app_user

Revision ID: b518f9fd7cf7
Revises: 7b85bd9f1045
Create Date: 2026-09-11 15:33:11.477550

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Alembic 이 사용하는 리비전 식별자.
revision: str = 'b518f9fd7cf7'
down_revision: str | Sequence[str] | None = '7b85bd9f1045'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 아래 두 인덱스(ix_rag_chunk_content_bm25, ux_rag_chunk_natural_key)에 대한
    # drop_index 를 autogenerate 가 끼워 넣었지만 손으로 지웠다. docs/erd/app.md의 경고대로,
    # 이 인덱스들은 SQLAlchemy 모델에 선언되지 않고 raw SQL 마이그레이션으로만 관리돼서
    # rag_chunk 와 무관한 변경에도 autogenerate가 "삭제 대상"으로 오판한다.
    op.add_column('app_user', sa.Column('gender', sa.Enum('female', 'male', 'unspecified', name='gender', native_enum=False, length=20), nullable=False, comment='가입 시 선택한 성별'))
    op.add_column('app_user', sa.Column('age_group', sa.Enum('10s', '20s', '30s', '40s', '50s_plus', name='agegroup', native_enum=False, length=20), nullable=False, comment='가입 시 선택한 연령대'))
    op.add_column('app_user', sa.Column('terms_agreed', sa.Boolean(), server_default='false', nullable=False, comment='이용약관·개인정보 처리방침 동의 여부. 가입 게이트라 사실상 항상 true만 저장된다'))
    op.add_column('app_user', sa.Column('terms_agreed_at', sa.DateTime(timezone=True), nullable=True, comment='약관 동의 시각(감사용). terms_agreed=false일 때는 NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_user', 'terms_agreed_at')
    op.drop_column('app_user', 'terms_agreed')
    op.drop_column('app_user', 'age_group')
    op.drop_column('app_user', 'gender')
    # ### end Alembic commands ###
