"""add ingredient_master table

Revision ID: db7c30b372f2
Revises: 0001_extensions
Create Date: 2026-09-09 17:31:02.709915

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# Alembic 이 사용하는 리비전 식별자.
revision: str = 'db7c30b372f2'
down_revision: str | Sequence[str] | None = '0001_extensions'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredient_master',
    sa.Column('ingredient_code', sa.Integer(), nullable=False, comment='KCIA 성분표준화명칭목록의 성분코드(원본 식별자)'),
    sa.Column('standard_name_ko', sa.Text(), nullable=False, comment='표준 성분명(국문)'),
    sa.Column('standard_name_en', sa.Text(), nullable=True, comment='표준 성분명(영문). PDF상 공란인 행이 있어 nullable'),
    sa.Column('old_names_ko', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False, comment="구 국문 명칭 목록. PDF의 '|' 구분 값을 분리해 저장"),
    sa.Column('old_names_en', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False, comment="구 영문 명칭 목록. PDF의 '|' 구분 값을 분리해 저장"),
    sa.Column('normalized_name_ko', sa.Text(), nullable=False, comment='표준 국문명에서 공백만 제거한 매칭용 키'),
    sa.Column('normalized_name_en', sa.Text(), nullable=True, comment='표준 영문명을 대소문자·공백·하이픈·괄호 기준으로 정규화한 매칭용 키'),
    sa.Column('source_version', sa.Text(), nullable=False, comment="KCIA 표준화명칭목록 발행 버전(예: '2026.08.31 기준')"),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='레코드 고유 식별자'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='레코드 생성 시각(UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='레코드 최종 수정 시각(UTC)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ingredient_code', name='uq_ingredient_master_ingredient_code'),
    comment='KCIA 표준화명칭목록 기반 성분 마스터. 성분 Entity Resolution용 사전',
    info={'managed': True}
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ingredient_master')
    # ### end Alembic commands ###
