"""add evidence table

Revision ID: f2fafa99fb94
Revises: aa0819863b09
Create Date: 2026-09-09 18:15:09.272001

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Alembic 이 사용하는 리비전 식별자.
revision: str = 'f2fafa99fb94'
down_revision: str | Sequence[str] | None = 'aa0819863b09'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidence',
    sa.Column('ingredient_id', sa.Uuid(), nullable=False, comment='근거가 적용되는 IngredientMaster 레코드'),
    sa.Column('topic', sa.Enum('cosmetic_use_restriction', name='evidencetopic', native_enum=False, length=40), nullable=False, comment='근거가 다루는 주제'),
    sa.Column('claim', sa.Text(), nullable=False, comment='핵심 결론'),
    sa.Column('conditions', sa.Text(), nullable=True, comment='결론이 성립하는 조건(사용 형태·농도·단서조항 등)'),
    sa.Column('jurisdiction', sa.Text(), nullable=False, comment='관할 국가/지역(예: 한국, EU, 중국)'),
    sa.Column('regulate_type', sa.Enum('prohibited', 'limited', name='evidenceregulatetype', native_enum=False, length=20), nullable=True, comment='MFDS 규제유형(금지/한도). MFDS 출처가 아니면 NULL'),
    sa.Column('cas_no', sa.Text(), nullable=True, comment='CAS 등록번호'),
    sa.Column('ingredient_synonym', sa.Text(), nullable=True, comment='이명(원본 콤마 구분 텍스트 그대로)'),
    sa.Column('notice_ingredient_name', sa.Text(), nullable=True, comment='고시원료명'),
    sa.Column('source_type', sa.Enum('mfds_restricted_ingredient', name='evidencesourcetype', native_enum=False, length=40), nullable=False, comment='근거 출처 종류'),
    sa.Column('source_title', sa.Text(), nullable=False, comment='출처 문서/API 이름'),
    sa.Column('source_url', sa.Text(), nullable=False, comment='출처 URL'),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True, comment='원 출처의 발행/개정 시각(있는 경우만)'),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='이 레코드를 수집한 시각'),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='레코드 고유 식별자'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='레코드 생성 시각(UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='레코드 최종 수정 시각(UTC)'),
    sa.CheckConstraint("regulate_type IS NULL OR regulate_type IN ('prohibited', 'limited')", name='ck_evidence_regulate_type'),
    sa.CheckConstraint("source_type IN ('mfds_restricted_ingredient')", name='ck_evidence_source_type'),
    sa.CheckConstraint("topic IN ('cosmetic_use_restriction')", name='ck_evidence_topic'),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient_master.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    comment='성분 안전성·규제 근거. CIR·MFDS 등 공식 출처만 담는다',
    info={'managed': True}
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evidence')
    # ### end Alembic commands ###
