"""smoke 10(2026-09-21)에서 실제로 저장된 PubMed 제목·초록 발췌. 필터 회귀 테스트용 fixture.

초록은 2500자까지만 발췌했다. 저장된 bundle 에는 MeSH/publication type 이 없어(chunk 에는 초록 본문만 있다)
MeSH 는 PubMed 가 세포 실험에도 붙이는 "Humans" 로 재구성했다. 이것이 예전 오분류를 재현하는 조건이다.
"""

FIXTURES: dict[str, dict[str, str]] = {
    "38299457": {
        "group": "niacinamide",
        "title": "Efficacy of ceramides and niacinamide-containing moisturizer versus hydrophilic cream in combination with topical anti-acne treatment in mild to moderate acne vulgaris: A split face, double-blinded, randomized controlled trial.",
        "abstract": "INTRODUCTION: Topical therapy is the mainstay treatment of acne, and topical retinoids such as tretinoin, tazarotene, and adapalene are recommended as the first-line therapy for mild to moderate acne. However, the cutaneous irritations may occur, and the dermocosmetics are recommended to prevent side effects of anti-acne drugs and adhere to treatment. Thus, this study aims to compare the efficacy and tolerability of ceramides and niacinamide-containing moisturizer (CCM) versus hydrophilic cream in combination with topical anti-acne treatment in mild to moderate acne vulgaris. METHODS: This was an 8-week, randomized, double-blinded, split face study in 40 patients assigned for topical anti-acne medications (5% benzoyl peroxide and 0.1% adapalene gel), then randomly applied CCM or hydrophilic cream. All patients were followed at week 0, 2, 4, and 8 for acne improvement, adverse reactions, biometric, and biophysical evaluation. RESULTS: CCM could significantly improve the non-inflammatory, inflammatory, and total acne lesions compared with hydrophilic cream after week 8 of treatment. Interestingly, there was an improvement of global worst score, hemoglobin index, melanin index, TEWL, skin hydration, sebum production, and skin surface pH, with no statistically significant differences between the two treatments. No serious side effects from clinical application of CCM and hydrophilic cream in mild to moderate acne vulgaris patients. CONCLUSION: Ceramide and niacinamide-containing moisturizer in combination with anti-acne medication can significantly improve acne lesions and decrease cutaneous irritations toward a satisfactory treatment outcome of mild to moderate acne vulgaris.",
    },
    "36683259": {
        "group": "niacinamide",
        "title": "Topical niacinamide (Nicotinamide) treatment for discoid lupus erythematosus (DLE): A prospective pilot study.",
        "abstract": "BACKGROUND: Cutaneous lupus erythematosus is an umbrella term for a group of autoimmune connective tissue disorders affecting the skin. Discoid lupus erythematosus (DLE) is the chronic condition and most common form of cutaneous lupus erythematosus. AIMS: Current therapies of DLE are challenging and not completely satisfactory, highly expensive, off-label, or poorly available (like antimalarials due to COVID-19 outbreaks). Nicotinamide, also called niacinamide, is a water-soluble form of vitamin B3 (niacin). Its multiple effects let us think that nicotinamide could be a therapy for lupus-associated skin lesions. METHODS: We performed a prospective randomized double-blind clinical trial on 60 subjects diagnosed with Discoid lupus erythematosus using topical Nicotinamide 2% and 4% preparations in form of cream and gel on skin and scalp lesions. Control group was included using only cream/gel base as placebo control. RESULTS: Obtained data showed that topical Nicotinamide can be used for the treatment of DLE as adjuvant to other treatment regimens with good cosmetic results and minimal side effects. Topical 4% Nicotinamide is superior to 2% preparation in response but associated with a higher incidence of irritation. CONCLUSION: Topical Nicotinamide can be used for the treatment of DLE as an adjuvant to other treatment regimens with good cosmetic results and minimal side effects. Further trials with long-term therapy, follow-up period, and bigger sample sizes are required.",
    },
    "40586182": {
        "group": "retinol",
        "title": "Novel Cyclized Hexapeptide-9 Outperforms Retinol Against Skin Aging: A Randomized, Double-Blinded, Active- and Vehicle-Controlled Clinical Trial.",
        "abstract": "BACKGROUND: The functionality and regenerative capacity of skin progressively deteriorate with aging. Topical use of peptides with a hyper-safety profile has been implicated in replacing retinol for skin anti-aging use, but is limited due to low stability and poor skin permeability. AIMS: In this randomized, double-blinded, active- and vehicle-controlled clinical trial, we aim to evaluate the efficacy of an innovative cyclized hexapeptide-9 (CHP-9) with increased stability and skin permeability on skin aging compared to retinol. METHODS: Healthy volunteers with aging skin were randomly assigned to twice-daily topical use of 0.002% CHP-9 serum, 0.002% retinol serum, or vehicle serum for 56\u2009days. RESULTS: CHP-9 treatment significantly decreased the number, area, and roughness of both crow's feet (-2.20, 95% CI: -4.38, -0.03; -3.95, 95% CI: -5.80, -2.11; -1.95, 95% CI: -3.30, -0.59, respectively) and forehead wrinkles (-2.88, 95% CI: -4.21, -1.56; -4.90, 95% CI: -5.97, -3.82; -3.96, 95% CI: -5.92, -2.01, respectively), while retinol only decreased the area of crow's feet (-2.23, 95% CI: -3.86, -0.60) and the number and area of forehead wrinkles (-1.05, 95% CI:-1.69, -0.41). Except for the roughness of crow's feet, CHP-9 demonstrated significantly larger extent of effects than retinol did on all other outcomes. Furthermore, long-term use of CHP-9 showed time-dependent augmentation in its potency to reduce the number of crow's feet, and the number, area, and roughness of forehead wrinkles. CONCLUSIONS: In conclusion, CHP-9 is more potent than retinol in improving skin aging-related symptoms, especially for long-term use. Cyclization of collagen peptides may present a preventive/therapeutic option for skin aging.",
    },
    "29947134": {
        "group": "retinol",
        "title": "Prospective, randomized, double-blind assessment of topical bakuchiol and retinol for facial photoageing.",
        "abstract": "BACKGROUND: Bakuchiol is a phytochemical that has demonstrated cutaneous antiageing effects when applied topically. Early studies have suggested that bakuchiol is a functional analogue of topical retinoids, as both compounds have been shown to induce similar gene expression in the skin and lead to improvement of cutaneous photodamage. No in vivo studies have compared the two compounds for efficacy and side-effects. OBJECTIVES: To compare the clinical efficacy and side-effect profiles of bakuchiol and retinol in improving common signs of cutaneous facial ageing. METHODS: This was a randomized, double-blind, 12-week study in which 44 patients were asked to apply either bakuchiol 0·5% cream twice daily or retinol 0·5% cream daily. A facial photograph and analytical system was used to obtain and analyse high-resolution photographs of patients at 0, 4, 8 and 12 weeks. Patients also completed tolerability assessment questions to review side-effects. During study visits, a board-certified dermatologist, blinded to study group assignments, graded pigmentation and redness. RESULTS: Bakuchiol and retinol both significantly decreased wrinkle surface area and hyperpigmentation, with no statistical difference between the compounds. The retinol users reported more facial skin scaling and stinging. CONCLUSIONS: Our study demonstrates that bakuchiol is comparable with retinol in its ability to improve photoageing and is better tolerated than retinol. Bakuchiol is promising as a more tolerable alternative to retinol.",
    },
    "15304189": {
        "group": "ascorbic",
        "title": "A double-blind randomized trial of 5% ascorbic acid vs. 4% hydroquinone in melasma.",
        "abstract": "BACKGROUND: Melasma is an acquired treatment-resistant hyperpigmentation of the skin. METHODS: Sixteen women with idiopathic melasma were included in our trial. After randomization by another clinician, they were instructed to use, at night, 5% ascorbic acid cream on one side of the face and 4% hydroquinone cream on the other side, for 16 weeks. Sunscreen was applied daily throughout the period of observation. They were evaluated every month by colorimetry, digital photography, and regular color slides. Subjective evaluation by each patient was also taken into account. RESULTS: The best subjective improvement was observed on the hydroquinone side with 93% good and excellent results, compared with 62.5% on the ascorbic acid side (P < 0.05); however, colorimetric measures showed no statistical differences. Side-effects were present in 68.7% (11/16) with hydroquinone vs. 6.2% (1/16) with ascorbic acid. CONCLUSION: Although hydroquinone showed a better response, ascorbic acid may play a role in the therapy of melasma as it is almost devoid of side-effects; it could be used alone or in combination therapy.",
    },
    "370586": {
        "group": "ascorbic",
        "title": "Ineffectiveness of ascorbic acid therapy in nephropathic cystinosis.",
        "abstract": "Because high concentrations of ascorbic acid (0.57 mM) lower the free (nonprotein) cystine content of cultured cystinotic skin fibroblasts by over 50 per cent, we did a double-blind clinical trial to establish whether this drug would benefit cystinotic children. Sixty-four patients were randomized into the study; 32 received ascorbic acid (200 mg per kilogram of body weight per day), and 32 placebo. The study was terminated after approximately two years because there was no indication that vitamin C was beneficial and accumulating evidence that it might be harmful. Of 11 patients who left the study because of death or the requirement for dialysis or renal transplantation, eight were receiving ascorbic acid. The estimated relative risk (treatment vs. control) of an adverse event was R = 2.7, with a 90 per cent confidence interval of (0.8, 11.5). The serum creatinine concentration increased 0.53 mg per deciliter per year in patients receiving vitamin C and 0.24 mg per deciliter per year in patients receiving placebo (P = 0.08).",
    },
    "42353265": {
        "group": "3oea",
        "title": "Skin Cells' Protection Against UVA-Induced Changes in Co-Cultured Keratinocytes-Fibroblasts' Proteome and Released Signaling Proteins by 3-O-Ethyl Ascorbic Acid.",
        "abstract": "UVA radiation affects communication between the cells that create the human skin. To prevent UVA-induced damage, there is a constant search for compounds protecting all skin cells and homeostasis in their communication. Therefore, the aim of this study was to evaluate the effect of 24 h incubation with 3-O-ethyl ascorbic acid (EAA; 150 µM) on the intracellular proteome of co-cultured keratinocytes and fibroblasts after UVA irradiation (total dose 15 J/cm2), and on the protein profiles released into the medium by both cell types. A proteomic approach (nanoHPLC/QOrbiTrap) allowed the identification of proteins significantly modified by UVA and EAA. In keratinocytes, UVA radiation enhanced expression of pro-inflammatory and pro-proliferative/keratinizing proteins and decreased expression of antiapoptotic and antioxidant proteins, while in fibroblasts, UVA radiation induced expression mainly of pro-inflammatory proteins, simultaneously decreasing levels of proteins involved in the antioxidant response and growth factors. Increased pro-inflammatory protein and decreased growth factor levels were also observed in the medium. EAA restored the levels of these proteins compared to control cultures. The results of this study show that EAA may protect epidermal and dermal cells by reducing levels of pro-inflammatory proteins, increasing antioxidant system activity in skin keratinocytes and fibroblasts, and normalizing intercellular signaling.",
    },
    "37652708": {
        "group": "3oea",
        "title": "The Anti-Inflammatory Action of Cannabigerol Accompanied by the Antioxidant Effect of 3-O-ethyl Ascorbic Acid in UVA-Irradiated Human Keratinocytes.",
        "abstract": "Excessive daily exposure of human skin to natural UVA radiation leads to impaired redox homeostasis in epidermal keratinocytes, resulting in changes in their proteome. Commonly used antioxidants usually exhibit protection in a narrowed range, which makes it necessary to combine their effects. Therefore, the aim of this study was to analyze the protective effect of cannabigerol (CBG) and 3-O-ethyl ascorbic acid (EAA), used separately and together, on the proteomic profile of UVA irradiated keratinocytes. Proteomic analysis with the use of the Q Exactive HF mass spectrometer, combined with biostatistic tests, performed on UVA-irradiated keratinocytes indicated enhanced and lowered expression of 186 and 160 proteins, respectively. CBG treatment after UVA irradiation reduced these numbers to 110 upregulated and 49 downregulated proteins, while EAA eliminated all these changes. CBG completely eliminated the UV-induced effect on the expression of pro-inflammatory proteins and significantly increased the level of proteins responsible for cellular locomotion. On the other hand, CBG reduced the level of UVA-induced 4-hydroxynonenal protein adducts fivefold, whereas EAA had no effect on this modification. At the same time, CBG and EAA did not modify the expression/structure of proteins in relation to the nonirradiated control keratinocytes in the case of an unaccompanied use or slightly modified the protein profile when used in a mixture. The combined protective effects of CBG on protein structure and EAA on protein expression profile allowed us to obtain a wider protection of cells against UVA radiation, compared with when the compounds were used alone. SIGNIFICANCE STATEMENT: Proteomic analysis of human skin cells allows to conclude that 3-O-ethyl ascorbic acid eliminates UVA-induced changes in the expression of keratinocyte proteins, while cannabigerol significantly reduces 4-hydroxynonenal protein adducts. The combined protective effects of cannabigerol on protein structure and of 3-O-ethyl ascorbic acid on protein expression profile allowed to obtain a wider protection of cells against UVA radiation.",
    },
    "39537961": {
        "group": "3oea",
        "title": "Proteomic analysis of the combined effects of cannabigerol and 3-O-ethyl ascorbic acid on kinase-dependent signalling in UVB-irradiated human keratinocytes.",
        "abstract": "Oxidative stress induced by medium-wavelength ultraviolet radiation (UVB) is one of the most dangerous environmental stressors for the skin. Therefore, various medicinal remedies aim to prevent the harmful effects of UVB or support the recovery of the damaged cells. This study aimed to evaluate the impact of bioactive phytocannabinoid cannabigerol (CBG) together with 3-O-ethyl ascorbic acid (EAA), a stable, lipophilic derivative of the antioxidant vitamin C, on UVB-induced changes of proteome in cultured human keratinocytes 24\xa0h after treatment. Surprisingly, proteomic analysis revealed very prominent CBG and EAA effects on kinases. These changes mainly influenced ERK1/2, IKK, MAP3K7, MAPK14, RIPK2, and NLK. Their expression was decreased by CBG and EAA, especially if used together after UVB-irradiation, so the effects of UVB were abolished restoring the profile of kinases to non-irradiated control. Moreover, CBG and EAA also reduced the UVB-induced modifications of proteins by the lipid peroxidation product 4-hydroxynonenal, especially in the case of AKT, Camkk1, cJun, ERK1, IKKα, MAPK11 and PERK. We conclude that, by maintaining proteome stability and kinase-dependent signalling, both CBG and EAA may support the recovery of human keratinocytes exposed to UVB radiation, especially if applied together, while the time-dependence of these effects should be further studied.",
    },
    "42196964": {
        "group": "centella",
        "title": "A Randomized, Double-Blind, Placebo-Controlled Trial Assessing the Effects of Oral Centella asiatica Extract on Skin Aging-Related Parameters in Middle-Aged Korean Women.",
        "abstract": "BACKGROUND: Centella asiatica has been widely recognized for its dermatological benefits; however, clinical evidence supporting the efficacy of oral supplementation for improving skin aging parameters remains limited. This randomized, double-blind, placebo-controlled study evaluated the effects of oral Centella asiatica extract on skin wrinkles and related skin parameters in middle-aged women. METHODS: A total of 112 participants were randomized to receive either Centella asiatica extract (200 mg/day) or placebo for 12 weeks. Skin wrinkle parameters were quantitatively assessed using a three-dimensional skin imaging system (PRIMOS®). Skin hydration, transepidermal water loss (TEWL), elasticity, and skin color (brightness and redness) were additionally measured using validated non-invasive instruments. Efficacy analyses were performed in the per-protocol population. RESULTS: After 12 weeks of supplementation, the Centella asiatica extract group demonstrated significant improvements in multiple wrinkle parameters compared with the baseline. Average wrinkle depth decreased by 11.1%, and the mean depth of the largest wrinkle decreased by 14.4%. Maximum wrinkle depth and total wrinkle volume were reduced by 13.3% and 13.7%, respectively, while surface roughness (Ra) decreased by 10.4%. In contrast, the placebo group showed minimal or inconsistent changes. Epidermal hydration at the cheek site significantly increased, while transepidermal water loss decreased, indicating improved skin barrier function. However, the magnitude of changes in epidermal hydration (2.7%), skin elasticity (R2; 0.7%), and skin brightness (L*; 0.7%) were relatively small. Skin elasticity and skin brightness showed statistically significant differences compared with the placebo group (p < 0.05), but these changes should be interpreted as modest improvements. No serious adverse events were reported, and all hematological and biochemical safety markers remained within normal reference ranges during the 12-week intervention period. CONCLUSIONS: Oral supplementation with Centella asiatica extract for 12 weeks was associated with improvements in wrinkle-related parameters and TEWL, while changes in skin hydration, elasticity, and brightness were modest and of limited magnitude. These findings suggest a potential role for short-term supplementation; however, further studies are required to confirm long-term efficacy and broader applicability.",
    },
    "41950551": {
        "group": "centella",
        "title": "Standardized Centella asiatica extract (ECa 233) mitigates chlorhexidine-induced cytotoxicity and promotes oral wound repair via immunomodulation and angiogenesis.",
        "abstract": "OBJECTIVE: Although 0.12% Chlorhexidine (CHX) is the gold standard oral antiseptic, its significant cytotoxicity often delays tissue repair. This study investigated the potential of ECa 233, a standardized Centella asiatica extract, to mitigate CHX-induced damage and promote oral wound regeneration. DESIGNS: Antimicrobial efficacy was assessed via minimum inhibitory concentration (MIC) against key oral pathogens. Human Gingival Fibroblasts (HGFs) were treated with CHX and ECa 233 to evaluate viability (MTT) and migration (scratch assay). Anti-inflammatory effects were measured by quantifying CD80 expression and cytokine secretion (TNF-alpha, IL-6) in LPS-stimulated U937 cells, while angiogenesis was evaluated using the chick embryo chorioallantoic membrane (CAM) assay. RESULTS: Results demonstrated that ECa 233 preserved the antimicrobial activity of CHX. While 0.12% CHX alone significantly inhibited HGF viability and migration (p\u202f<\u202f0.001), the addition of 0.05% ECa 233 significantly rescued these cellular parameters (p\u202f<\u202f0.05). ECa 233 effectively downregulated the M1 macrophage marker CD80 and suppressed the secretion of TNF-alpha and IL-6, indicating potent immunomodulatory activity. Furthermore, ECa 233 significantly enhanced vascular density and branching complexity in the CAM assay (p\u202f<\u202f0.005). CONCLUSION: The ECa 233-CHX formulation maintains essential antimicrobial efficacy while reducing cytotoxicity and actively promoting fibroblast migration, immunomodulation, and angiogenesis. This dual-action approach addresses the clinical limitation of antiseptic-induced tissue toxicity, offering a superior biological strategy for enhancing oral wound healing and post-surgical recovery.",
    },
    "36278820": {
        "group": "centella",
        "title": "Centella asiatica extract-SiO2 nanocomposite: More than a drug-delivery system for skin protection from oxidative damage.",
        "abstract": "An innovative nanotechnology-based approach was used for the preparation of Centella asiatica (C. asiatica) extract-SiO2 nanocomposites, specifically tailored for skin protection from oxidative damage. Different amounts of C. asiatica glycolic extract (1.0, 3.0, 5.0, and 10.0\xa0wt\xa0%) and fumed silica were used to prepare the nanocomposites by means of ball milling method. The influence of both composition of the starting mixture and milling time on the final products was evaluated by different techniques such as X-ray powder diffraction, scanning electron microscopy, infrared spectroscopy, thermogravimetric analysis, and nitrogen sorption analysis. Results confirmed the integrity of the natural extract after the milling process, and its successful loading in the silica matrix. No cytotoxicity was observed for the obtained nanocomposites, which showed high in-vitro ability to scavenge 2,2-diphenyl-1-picrylhydrazyl and to protect human keratinocytes from damages induced with hydrogen peroxide.",
    },
    "41422283": {
        "group": "hyal",
        "title": "Oral sodium hyaluronate improves skin hydration, barrier function and signs of aging: a randomized, double-blind, placebo-controlled trial in 150 healthy adults.",
        "abstract": "Oral hyaluronan has been reported to improve various aspects of skin physiology, but existing trials often lack methodological rigor, comprehensive outcome assessment, and diverse populations. This randomized, double-blind, placebo-controlled trial evaluated the effects of sodium hyaluronate (SH) supplementation at two daily doses on skin parameters in healthy Caucasian adults. A total of 150 participants were randomized to receive SH (1.8 MDa) at 60\xa0mg/day (SH60), 120\xa0mg/day (SH120), or placebo for 12 weeks. Facial hydration, transepidermal water loss (TEWL), sebum, elasticity, wrinkle depth, skin gloss, colorimetric parameters, epidermal thickness, dermal density, red areas, and pore size were assessed at baseline and monthly. Subjective skin condition was evaluated every two weeks, and components of natural moisturizing factor (NMF) in forearm skin were quantified by LC-MS/MS. SH120 significantly enhanced skin hydration and elasticity, while reducing TEWL, sebum, and periorbital wrinkle depth versus placebo. It also improved skin structure by increasing epidermal thickness, dermal density, and NMF levels. SH60 showed similar but more modest effects. No changes were observed for colorimetric parameters, red areas, pore size, or gloss. In conclusion, oral SH supplementation improved multiple aspects of skin physiology, supporting its use as a functional food ingredient with measurable benefits for skin health and healthy aging.Trial registration: ClinicalTrials.gov, NCT07065110 (retrospectively registered on 15 Jul 2025); EFSA (European Food Safety Authority) registry: EFSA202400027979 (prospectively filed on 06 Jun 2024).",
    },
    "41117156": {
        "group": "hyal",
        "title": "Efficacy and safety of injectable sodium hyaluronate with vitamin C, tranexamic acid, and glutathione for pigmented dark circles.",
        "abstract": "BACKGROUND: Periorbital hyperpigmentation (POH) is a common benign condition affecting facial esthetics. This study evaluated the efficacy and safety of an injectable sodium hyaluronate complex solution combined with vitamin C, tranexamic acid, and glutathione for POH treatment. METHOD: 120 POH patients were randomly divided into two groups. All participants received two treatment injections at two-week intervals. Evaluations were conducted at 4 and 12\u2009weeks posttreatment, assessing periorbital grayscale values, clinical grading changes, Global Esthetic Improvement Score, Dermatologic Quality of Life Index (DLQI), and patient satisfaction. RESULT: The treatment group demonstrated significant improvements in grayscale values (162.10\u2009±\u200914.22 to 169.66\u2009±\u200913.43) and reduced pigmentation differences from normal skin (23.01\u2009±\u200912.73 to 14.44\u2009±\u200914.79). The control group showed no significant changes. Treatment group patients exhibited significantly better grayscale values (p\u2009<\u2009.05), improved DLQI scores, and reduced dark circle severity (p\u2009<\u2009.05). 96.7% of treated patients reported satisfaction with visible esthetic improvements. CONCLUSION: The hyaluronate-based combination therapy effectively improved POH, demonstrating significant esthetic enhancement and quality of life improvement. This minimally invasive approach proved safe, effective, and highly satisfactory, presenting a promising treatment option for periorbital hyperpigmentation. EVIDENCE LEVEL: Level II.",
    },
    "24724824": {
        "group": "hyal",
        "title": "Liposome, gel and lipogelosome formulations containing sodium hyaluronate.",
        "abstract": "The moisture-imparting effect of sodium hyaluronate (Na-HA) was investigated in liposome, gel and lipogelosome topical formulations. Sixteen liposome formulations were prepared with or without Na-HA (45 kDa) using various ratios of dimyristoylphosphatidylcholine, 1,2-dimyristoyl-sn-glycero-3-phosphatidylglycerol, dipalmitoylphosphatidylcholine and phospholipon 100H. The liposomes were characterized in terms of their structure, composition, zeta potential, Na-HA-entrapment capacity and stability. In particular, scanning electron microscopy, polarized light microscopy, dynamic light scattering and atomic force microscopy were utilized to probe appearance, size and size distribution and lamellarity. The work was then extended to gels using the gelling agents poloxamer (PXM 188 or 407) and Carbopol or Ultrez 21 (U-21), yielding liposome-loaded gel formulations (i.e. lipogelosomes). The in vitro release kinetics of Na-HA from liposomes, lipogelosomes and commercial Na-HA reference formulations were studied via a flow-through cell method. Among the liposomal formulations tested, L6, comprising of Na-HA-loaded phospholipon 100H:stearylamine:cholesterol (7:1:2), displayed optimal traits. The mean particle size, zeta potential and entrapment capacity of L6 were determined as 1900 nm, -20.9 mV and 15.0%. The optimum lipogelosome, LG4, was obtained by incorporating liposome L6 into a U-21 gel at a ratio of 1:1 (w/w). In clinical trials, in-house formulations were applied twice daily to 15 female volunteers. The two-week benefits were assessed against a commercial product; and in all cases, changes of skin humidity, sebum content, pH and wrinkle depth were promising. In particular, the LG4 lipogelosome-based formulation had significantly improved skin hydration and compliance, as evidenced by a moisture content gain of 30.4%.",
    },
    "26362110": {
        "group": "collagen",
        "title": "The effect of oral collagen peptide supplementation on skin moisture and the dermal collagen network: evidence from an ex vivo model and randomized, placebo-controlled clinical trials.",
        "abstract": "BACKGROUND: Skin dryness and an accelerated fragmentation of the collagen network in the dermis are hallmarks of skin aging. Nutrition is a key factor influencing skin health and consequently its appearance. A wide range of dietary supplements is offered to improve skin health. Collagen peptides are used as a bioactive ingredient in nutricosmetic products and have been shown in preclinical studies to improve skin barrier function, to induce the synthesis of collagen and hyaluronic acid, and to promote fibroblast growth and migration. Our aim was to investigate the effect of oral supplementation with specific collagen peptides on skin hydration and the dermal collagen network in a clinical setting. METHODS: Two placebo-controlled clinical trials were run to assess the effect of a daily oral supplementation with collagen peptides on skin hydration by corneometry, on collagen density by high-resolution ultrasound and on collagen fragmentation by reflectance confocal microscopy. Human skin explants were used to study extracellular matrix components in the presence of collagen peptides ex vivo. RESULTS: Oral collagen peptide supplementation significantly increased skin hydration after 8 weeks of intake. The collagen density in the dermis significantly increased and the fragmentation of the dermal collagen network significantly decreased already after 4 weeks of supplementation. Both effects persisted after 12 weeks. Ex vivo experiments demonstrated that collagen peptides induce collagen as well as glycosaminoglycan production, offering a mechanistic explanation for the observed clinical effects. CONCLUSION: The oral supplementation with collagen peptides is efficacious to improve hallmarks of skin aging.",
    },
    "37822045": {
        "group": "collagen",
        "title": "Low-molecular-weight collagen peptides supplement promotes\xa0a healthy skin: A randomized, double-blinded, placebo-controlled study.",
        "abstract": "BACKGROUND: Oral collagen peptides supplementation was reported to improve skin integrity and counteract skin aging. AIMS: A randomized, double-blinded, placebo-controlled study was conducted to clinically evaluate the impact of low-molecular-weight collagen peptides on the human skin. PATIENTS/METHODS: Healthy adult participants (n\u2009=\u2009100) were randomly assigned to receive a test product containing low-molecular-weight collagen peptides or a placebo. Parameters of skin wrinkles, elasticity, hydration, and whitening (melanin and erythema indexes) were measured at baseline and after 4, 8, and 12\u2009weeks. RESULTS: Compared with the placebo group, the average skin roughness, maximum of all peak-to-valley values, maximum peak height of the wrinkle, and average maximum height of the wrinkle were significantly improved in the test group. Parameters of skin elasticity, including overall elasticity, net elasticity, and biological elasticity, were also significantly improved in the test group at Week 12 as compared with the placebo group. Moreover, skin hydration and whitening parameters changed more significantly in the test group than in the placebo group. None of the participants experienced adverse events related to the test product. CONCLUSIONS: Taken together, these findings suggest that low-molecular-weight collagen peptides supplementation can safely ehance human skin wrinkling, hydration, elasticity, and whitening properties.",
    },
    "33742704": {
        "group": "collagen",
        "title": "Effects of hydrolyzed collagen supplementation on skin aging: a systematic review and meta-analysis.",
        "abstract": "Skin aging has become a recurring concern even for younger people, mainly owing to increased life expectancy. In this context, the use of nutricosmetics as supplements has increased in recent years. Moreover, numerous scientific studies have shown the benefits of hydrolyzed collagen supplementation in improving the signs of skin aging. The objective of this study was to summarize the evidence on the effects of hydrolyzed collagen supplementation on human skin through a systematic review followed by a meta-analysis of clinical trials focusing on the process of skin aging. A literature search was conducted in the Medline, Embase, Cochrane, LILACS (Latin American and Caribbean Health Sciences Literature), and Journal of Negative Results in BioMedicine databases. Eligible studies were randomized, double-blind, and controlled trials that evaluated oral supplementation with hydrolyzed collagen as an intervention and reported at least one of the following outcomes: skin wrinkles, hydration, elasticity, and firmness. After retrieving articles from the databases, 19 studies were selected, with a total of 1,125 participants aged between 20 and 70\u2009years (95% women). In the meta-analysis, a grouped analysis of studies showed favorable results of hydrolyzed collagen supplementation compared with placebo in terms of skin hydration, elasticity, and wrinkles. The findings of improved hydration and elasticity were also confirmed in the subgroup meta-analysis. Based on results, ingestion of hydrolyzed collagen for 90\u2009days is effective in reducing skin aging, as it reduces wrinkles and improves skin elasticity and hydration.",
    },
    "28115641": {
        "group": "bha",
        "title": "Endocrine Activity of AVB, 2MR, BHA, and Their Mixtures.",
        "abstract": "Personal care products are used increasingly, resulting in growing concern concerning their potential disruption of normal hormonal functions. Recent results on the bioaccumulation of cosmetic ingredients in wildlife and humans point to the need for an in-depth analysis for endocrine activity, in particular with respect to their influence on the androgen (AR), glucocorticoid (GR), and thyroid hormone receptors (TRs). Furthermore, humans are commonly exposed simultaneously to complex mixtures of endocrine active compounds. We have therefore examined 3 frequently used cosmetic ingredients: 2-methylresorcinol (2MR), butylated hydroxyanisole (BHA) and avobenzone (AVB), for (anti)-androgen-, (anti)-glucocorticoid-, and (anti)-thyroid hormone-like activities. Their binary and ternary mixtures at EC50 or IC50 concentrations have also been examined for anti-androgen-, glucocorticoid-, and thyroid hormone-like activities. In the MDA-kb2 reporter cell line, compounds possessed anti-androgen-, glucocorticoid-, and anti-glucocorticoid-like activities (except AVB). A new cell line, GH3.TRE-Luc, was used to evaluate anti-thyroid and thyroid hormone-like activities. The combinations 2MR + BHA and 2MR + BHA + AVB have glucocorticoid-like activity: only 2MR + AVB has anti-androgen-like activity. On the other hand, binary and ternary mixtures of compounds showed no thyroid hormone-like activity. Thus, in addition to identifying new endocrine disrupting compounds, it is also necessary to determine the effects of their mixtures in order to assess fully their risk to human health.",
    },
}
